# Generated by Django 4.2.1 on 2023-08-06 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('text', models.CharField(
                    max_length=25
                )),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('uuid', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    unique=True
                )),
                ('name', models.CharField(
                    max_length=25
                )),
                ('prompt', models.CharField(
                    max_length=250
                )),
                ('type', models.IntegerField(
                    choices=[
                        (0, 'normal'),
                        (1, 'win-ending'),
                        (2, 'lose-ending')
                    ],
                    default=0
                )),
                ('choice_1', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='room_choice1',
                    to='dungeon.choice',
                    null=True,
                    blank=True
                )),
                ('choice_2', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='room_choice2',
                    to='dungeon.choice',
                    null=True,
                    blank=True
                )),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='room',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='linked_choices',
                to='dungeon.room'
            ),
        ),
    ]
