# Generated by Django 4.2.1 on 2023-08-07 03:40

from django.db import migrations

def forwards(apps, schema_editor):
    Room = apps.get_model("dungeon", "Room")
    Choice = apps.get_model("dungeon", "Choice")

    # Endings
    win_room = Room.objects.create(
        name = "YOU WIN!",
        prompt = "Whether by wits, skill or (most likely) blind luck, "\
                "you escaped the Djungeon!",
        type = 1,
    )
    lose_room = Room.objects.create(
        name = "YOU LOSE",
        prompt = "Maybe it was that potion you drank, or you took a bad turn. "\
                "Whatever it was, the Djungeon has claimed another soul...",
        type = 2,
    )

    # Initial Room
    win_choice = Choice.objects.create(
        text = "Turn Left",
        room = win_room,
    )

    lose_choice = Choice.objects.create(
        text = "Turn Right",
        room = lose_room,
    )

    Room.objects.create(
        name = "The Corridor of Choice",
        prompt = "You find yourself at a junction, do you...",
        choice_1 = win_choice,
        choice_2 = lose_choice,
    )

def reverse(apps, schema_editor):
    Room = apps.get_model("dungeon", "Room")
    Room.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
